version: '3'
services:
  qbittorrent:
    image: linuxserver/qbittorrent:14.3.9
    container_name: qbittorrent
    environment:
      - TZ=Asia/Shanghai
      - PUID=0
      - PGID=0
    volumes:
      - /data/docker/qbittorrent:/config
      - /data/download/:/data/download/
    ports:
      - 8080:8080
      - 45012:45012
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"