version: '3'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      - DOCKER_API_VERSION=1.52
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --interval
      - "86400"
      - --cleanup
      - --label-enable
      - --notifications-level
      - info